### ISSUE TITLE
Dashboard: automatically flag repeat scans and regenerate QC pages?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1003]
1. I *think* repeat scans (e.g.., _01_02) aren't being flagged in any way in the Dashboard. So, if a repeat is done, there's no visual cue to go in and review the data (e.g., the repeat scan doesn't show up on QC to-do list). Could we add some kind of indication?

2. Relatedly, qc-report doesn't attempt to generate a page if one page exists in the QC folder already, so data from 'repeated' scans (e.g., _01_02) is not represented on the QC pages. It's fine for us to  regenerate the page, but as the Dashboard is shared with others, it would probably be better if re-generation in the case of repeats was done automatically.

@DESm1th had some thoughts on what to do on related closed discussion #1001!

**Comment by edickie** [comment]
Flagging repeat scans was the original reason for the orginal default
(opposite of "--no-older") functionality of dm-qc-todo.py. We thought that
having the program report when the qc page was older than the data on the
filesystem we would get an alert of repeat scans. Instead, pages of every
change to the file system that happened after a qc page was signed off on.
So that was a fail.

Just putting this note to say that getting a computer to identify
repeat-scans that have not been qced is actually really hard to do...We
should give this a good think before implementing any changes because they
are likely to be very buggy..

**Comment by tomwright01** [comment]
`dm2-xnat-extract.py` now detects repeat scans and updates a repeat_number field in the session table of the database. There is also a last_repeat_qcd field that is updated when a visual quality control check is performed. Sessions are listed as requiring QC when last_repeat_qcd < repeat_number.

Does it make sense to integrate dm-qc-report.py with a similar mechanism to determine if a sessions needs re-running with the --rewrite flag?

It would be simple to implement this through the datman/dashboard.py module.

**Comment by josephdviviano** [comment]
@tomwright01 that makes a lot of sense to me. dm-qc-report generates a series of subjects to run. It could, for each, just check whether it needs the re-write flag or not, and then submit the appropriate command (with or without --rewrite) in the loop.

**Comment by DESm1th** [comment]
I think if we put that logic in dm-qc-report it could be messy. That script doesn't have access to the last_repeat_qcd value so it could just end up accidentally running rewrite on every scan with a repeat every time it's run. It might be better to just add a call in the dashboard logic that runs dm-qc-report when it finds a repeat that needs to be qc'd, since it's already done the hard work of identifying those sessions

**Comment by josephdviviano** [comment]
@DESm1th that makes sense

**Comment by tomwright01** [comment]
Currently dashboard doesn't trigger any datman style events (data upload, download, processing). 
The datman scripts do however feed into dashboard.

For now I have modified datman/scan.py to give access to the dashboard session object `Scan.get_db_object()`. 
`dm-qc-report.py` uses this to check if there is repeat data for the session.
