### ISSUE TITLE
/archive/code/bin/run.sh: line 54: kill: (34852) - No such process

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1005]
Either `dm_log_server.py` is dying, or the PID isn't correct.

I'm replacing the `$!` (which might work in some cases) with `ps axf | grep dm_log_server.py | grep -v grep | cut -d ' ' -f 1`, which should work in all cases, in `/archive/code/bin/run.sh`.

**Comment by DESm1th** [comment]
Hey Joe,

The actual issue here is that in order to allow the log server output files to be named and separated by date I took the easy way and just had run.sh start the server and then kill it for each run. I was hoping the jobs wouldn't overlap often enough for it to be an issue but it seems fairly often job A will finish after Job B starts, so Job B will get an error when it tries to start the server and then later try to kill a bad PID. 

I'm going to fix this up a bit today and set the server up so it doesn't need to be killed and restarted for separate log files to be made.

**Comment by josephdviviano** [comment]
Hi @DESm1th , does this mean that `run.sh` is taking over 24 hrs to run?

**Comment by DESm1th** [comment]
Yeah, it must be. And it seems to be taking that long about half the time or more, from looking at the logs since I've added the server in

**Comment by josephdviviano** [comment]
That's interesting + bad.

I think we should do a few things:

A) run the `run_data_kimel.sh` scripts in parallel
B) Move the log server kill to before the permissions manipulations (which take an extremely long time).

**Comment by DESm1th** [comment]
I think it would be a good idea to run them in parallel. I had put the kill after the permissions just in case a lot of qc-report jobs are submitted though, since there's no way to tell how long the server needs to be up to catch logging from those. I'm going to work on a way to change the log server so it doesn't need to be killed at all, and hopefully allow it to determine which program is doing the logging in case we want more than one script use it in the future.

**Comment by josephdviviano** [comment]
OK, I'll leave the kill command where it is, and I'm just using `&` to run the scripts in parallel:

`su -c "$project/bin/run_data_kimel.sh" - clevis &`

**Comment by DESm1th** [comment]
Ok! I've finished updating the logging server and given it a few small test runs and this shouldn't be an issue anymore. Also, the logs in /archive/logs/server_logs will now contain the name of the program logging to it, so any script that uses the queue can now be quickly modified to use it as well.

**Comment by DESm1th** [comment]
Oh, forgot to mention: I killed today's log server process and started up the new server script so today's log will also have the "No such process" error.
