### ISSUE TITLE
QC PACTMD data for grant analysis

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#1013]
Plotting some cortical thickness measures for these data, I already see some extreme outliers. @DESm1th has offered to QC some of the data and investigate the cause of any missing outputs (which I will also be doing as I continue the analysis).

**Comment by DESm1th** [comment]
Just as an update, after looking at the pipelines output, the following stuff needs to be fixed (I'm working on it now):

- Most participants dont have enigma dti output due to a small error in the analysis script that Erin pointed out. Should be an easy fix (and hopefully no other issues).
- Some participants are missing freesurfer outputs entirely, or missing a few outputs. Erin also helped me identify the cause and it should be another pretty easy fix.
- The rest pipeline hasn't been run on PACTMD at all since Joe updated his script (the rest outputs stored in the data folder are old). Not sure yet why this is, but I'll investigate as soon as possible

**Comment by DESm1th** [comment]
Ok all of the pipelines output for enigmaDTI and freesurfer should be there except for two people who don't have _FA files in dtifit for some reason (trying to figure why now) and one person whose freesurfer job crashed (re-running it now).

I also looked at the QC pages that are generated in dtifit and enigmaDTI and dealt with anything that was obviously wrong. I don't know enough to do a great job of QCing the enigmaDTI qcskel images though. 

The only thing I wasnt sure how to deal with was that the participant with IDs PACTMD_CMH_0110004_01, PACTMD_CMH_0110004_02, and PACTMD_CMH_0110004_03 has a weird space near the front of their brain that causes 'holes' in the enigmaDTI outputs. Their DTI images weren't blacklisted by the people who QC'd them though so I guess just be aware of this?
