### ISSUE TITLE
Dashboard: Figure out a process for deleting blacklisted scans from filesystem

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1017]
ATM, scans blacklisted via the Dashboard aren't being automatically deleted, and we aren't giving access to external users to delete the blacklisted scans. 

But, as far as I know, no-one has been going through the blacklist to manually delete the data.... at least, I haven't been (and this may cause some pipelines to mess up - sorry!).

Can you please either (1) suggest a process for reviewing/deleting blacklisted data or (2) add this as an automatic process?

:)

**Comment by DESm1th** [comment]
Hmm. I wrote a script months ago that does this but it's currently not
being run automatically. I'll show you tomorrow

**Comment by navonacalarco** [comment]
Doh! Thanks!

**Comment by djoverton** [comment]
Does @DESm1th's script solve this problem?

**Comment by DESm1th** [comment]
I wrote a more robust one in python that we can run nightly and just merged it in (with unit tests!). This should do the trick but I believe some clean up needs to be done in SPINS still before it can safely be run nightly. Do the blacklist file entries still need to be modified after the naming issue that we had?

**Comment by navonacalarco** [comment]
@DESm1th I manually modified the blacklist weeks ago; I believe everything there now reflects the MPRC renaming issue. So, I believe we can go ahead!

Let's just double check with @edickie!

**Comment by navonacalarco** [comment]
@edickie In your view, is everything set up so that we can run this automatically with Dawn's script? I updated the blacklist so that SPINS MPRC blacklist information reflects the new, correct naming.

**Comment by edickie** [comment]
yes let;s go ahead

**Comment by DESm1th** [comment]
I've added the blacklist removal to our nightly run scripts, so anything blacklisted should be removed within 24hrs. I'll update the pipelines scripts to check the blacklist as well, since the different formats of our pipelines outputs make it hard to purge blacklisted data if it gets run through. Only issue is that we run our pipelines scripts on the scc and I dont think we ever update the scc's copy of datman... 

The removal script can also be run from the command line with:
dm_blacklist_rm.py $study

And on a single series with:
dm_blacklist_rm.py $study $series
