### ISSUE TITLE
each pipeline folder should have documentation

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1080]
We'll need to meet about this to hammer out the details.

**Comment by djoverton** [comment]
Want to meet about this today?

**Comment by edickie** [comment]
Sure, just let me finish putting the PRELAPSE numbers together first..

**Comment by josephdviviano** [comment]
pipelines to document:

- [ ] fmri
- [ ] ea
- [ ] imob
- [ ] freesurfer
- [ ] maget brain
- [ ] dtifit
- [ ] dtiprep
- [ ] enigma
- [ ] CIVET
- [ ] hcp

**Comment by josephdviviano** [comment]
Here's an example:

https://github.com/TIGRLab/datman/wiki/fmri-pipeline

**Comment by navonacalarco** [comment]
This is wonderful, guys! Thanks! :+1:

**Comment by edickie** [comment]
There's been some discussion that the documentation should go in the tigrlab wiki instead of the datman wiki where scientist are more likely to look...

Also, having them in the tigrlab wiki will allow us to add pictures without having to include them in the datman repo.

I'm going to make links between the two wikis...

**Comment by josephdviviano** [comment]
sounds good to me

we could even move them to our website proper (when we're done and everything). the github wikis are easy to forget about.

**Comment by djoverton** [comment]
Created an ASL pipeline documentation page using my project README.md as a template (still pretty detailed).
