### ISSUE TITLE
TDCS_CMH_001_01: visuals missing for fMRI data 

### ISSUE THREAD

**Issue by JessDArcey** [TIGRLab/admin#1084]
Hi All - all 6 fMRI runs were completed but the visuals are not showing up for me to inspect.

**Comment by navonacalarco** [comment]
Thanks Jess! We're on the case!  :)

**Comment by DESm1th** [comment]
This has been fixed.

**Comment by navonacalarco** [comment]
Thanks @DESm1th ! 

For posterity: Dawn pointed out the issue was that the novel TDCS fMRI tag hadn't been added to the DATMAN QC script - so, I need to remember to add to a study's tags to both (1) project settings, as was completed, and (2) make sure everything in project settings also exists in DATMAN, which was not the case.
