### ISSUE TITLE
Dashboard omitting certain series for subjects with repeat sessions (and linked scans)

### ISSUE THREAD

**Issue by DESm1th** [TIGRLab/admin#1197]
For some subjects (e.g. SPN01_CMH_0104_01) that have multiple sessions, series that don't have QC metrics (like T1s and PDT2s) are being omitted from the dashboard's list of series. Linked scans are also being left out (see PNS_CMH_0027_01, who gets their data from SPN01_CMH_0104_01)

**Comment by tomwright01** [comment]
Hi Dawn,
Looked this morning and all the expected data seems to be in the dashboard.
There are a couple of oddities:
1. a record for a RST scan (id:13) 
    This has an entry in blacklist, so should have been removed from our file system. 
    scanid:13 for the _01 session is an EATask. 
    Only the EATask scan exists in the zipfile
    qc outputs exist for both RST and EATask
    

2. a record for a DTI scan (id: 14)
   scanid: 14 refers to another EATask. 
   Only the EATask exists in the zip file.
   qc outputs exist for both DTI and EATask

Notes indicate that the session was repeated due to technical issues with the scanner. My guess is that the zipfile has been updated and we now have the correct information.

**Comment by tomwright01** [comment]
Scans without QC metrics are now added to the dashboard.
Linked scans are more of a problem. closing this is favour of #1275
