### ISSUE TITLE
EA Video 6

### ISSUE THREAD

**Issue by loliver4** [TIGRLab/admin#1242]
The number of timepoints we're actually getting from EA video 6 (which aligns with the timing of the video itself) is actually 72 versus the current 99 in the gold standard.

**Comment by josephdviviano** [comment]
Thanks!

I need to check some things with you about the raw data.

If you look at the ('durations' file)[https://github.com/TIGRLab/datman/blob/master/assets/EA-vid-lengths.csv] and the ('ratings' file)[https://github.com/TIGRLab/datman/blob/master/assets/EA-timing.csv] the numbers don't line up.

Meaning, the length of vid6 according to the duration file is 144 while the ratings file has 99 entries.

I need to truncate the ratings file from 99 entries down to 72 (by cutting off the end).

I think the duration is seconds, meaning 144 seconds, and since the number of ratings is meant to be 72 (at 2 second intervals), this **implies I don't need to change the duration**.

Please confirm :)

**Comment by loliver4** [comment]
Exactly! That duration (144 seconds) is correct (confirmed based on the debug outputs you kindly generated and the video duration at the scanner), hence the 72 entries instead of 99.

**Comment by josephdviviano** [comment]
Great! I'm pushing the changes now. Will re-run all EA data over the weekend.

**Comment by loliver4** [comment]
Awesome! Thanks so much!

**Comment by josephdviviano** [comment]
My pleasure
