### ISSUE TITLE
PNSC qc error -- no list generated on dashboard?

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1258]
@tomwright01 if you want to walk Dawn and myself through this error / the fix that would be helpful!!

http://srv-dashboard.camhres.ca/study/17
**QC to-do: Error:An error occured getting the QC list. The admins have been notified. other**

**Comment by tomwright01** [comment]
Happy to walk through this (I'm at CMH tomorrow), however the probable
cause is a timeout of dm-qc-todo.py If it's network issue it'll probably
resolve itself.

**Comment by DESm1th** [comment]
Tom pointed out that this issue, https://github.com/TIGRLab/admin/issues/1261 and https://github.com/TIGRLab/admin/issues/1259 are all due to the dashboard still including output from the deprecated dm-qc-todo script. Tom and I both seem to agree that we should just remove the duplicated qc todo section since the database is more reliable and reports the same information (more accurately).

**Comment by josephdviviano** [comment]
+1

**Comment by tomwright01** [comment]
This issue revealed some poorly commented code (particularly `dashboard/templates/study.html`. I have updated this (not yet pushed). I'll remove the calls to `dm-qc-todo.py` next week.

**Comment by tomwright01** [comment]
Removed client side references to dm-qc-todo.py.
