### ISSUE TITLE
tractmap and dtiprep jobs being resubmitted?

### ISSUE THREAD

**Issue by tomwright01** [TIGRLab/admin#1266]
There seem to be too many DTIPrep and TractMap jobs being submitted nightly. My guess is these subjects are failing for some subject specific reason. Will investigate.

**Comment by DESm1th** [comment]
I think there may be an issue with our local queue (just a guess). I
noticed yesterday that QC reports arent being generated either even though
the jobs submit correctly and the subjects run just fine individually.
There are also a ton of dead jobs on the queue.

Didnt get a chance to look into it further yet.

**Comment by josephdviviano** [comment]
@DESm1th  I suspect these are unrelated.

Some machines are having trouble resolving 'clevis' over NIS. Likely related to the IPA changes a few weeks back.

Tom's issue of the code being run nightly is likely unrelated, because these jobs run for a long time. I suspect they are getting stuck somewhere. If it was an authentication issue they would fail instantly.

**Comment by tomwright01** [comment]
Found a bug in `dm-launch-tractmap.py` that was causing tractmap to be launched for __b3000__ scans. These failed and were being resubmitted.

DTIPrep problems are probably related to #1267
