### ISSUE TITLE
Dashboard: link to REDCap 'scan completed' not working (?)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1281]
Hey guys,

I might be wrong, but it looks like the Dashboard isn't updating with 'scan completed' information kept in REDCap.

For example, SPN01_CMH_0145_01 and SPN01_CMH_0143_01 are listed in the Dashboard as having "No Redcap record available", but both do have records in the 'scan completed' database.

What script should be run to fix this?

**Comment by DESm1th** [comment]
This might be related to the bug fixes I've been writing in response to the 'DTI' bug. Or to the ongoing issues with database client authentication. I'll look in to it.

**Comment by navonacalarco** [comment]
Thanks Dawn!

**Comment by DESm1th** [comment]
Ok so I fixed two problems related to the scan completed form, but I'm not sure if there are additional issues lurking.

Basically: 

- If a form was updated, it caused an error and the dashboard database copy of the record was not updated. This has been fixed.
- If a form had a long-ish comment (longer than 1024 characters) it was too large to fit in the database column and caused a crash. I increased the allowed length to 3072, so this hopefully will not happen again.

I'm not 100% sure if the dashboard or datman has any code to update redcap records after their creation, if not (and it doesn't look like it does) the missing comments will not be filled in because the data entry trigger was missed. But all future redcap info should be entered into the database without issue.

Additionally there may be other issues that may have contributed to this so if more redcap seems to be missing (and it was added after today - August 24th, 2017) then let me know and I'll do some more debugging.

**Comment by navonacalarco** [comment]
I'll add a character limit of < 3072 to REDCap. Thanks Dawn!

**Comment by navonacalarco** [comment]
@DESm1th Sorry, I see that the record for SPN01_CMH_0145_01 is now present, but SPN01_CMH_0143_01 still indicates "No Redcap record available" though there is indeed a record. I noticed it's 1169 characters. As you increased the allowed length, can we get this in?

**Comment by DESm1th** [comment]
Hey Navona, the reason for this is as I stated before: the dashboard doesn't seem to add a record once it misses the original data entry trigger. The reason SPN01_CMH_0145_01 is now present is because I was using that as a test record and went into redcap and updated the scan completed form (without making changes) to test that the fix worked. Other records from before the fix will not show up unless I manually do the same thing

**Comment by navonacalarco** [comment]
So you're saying the solution is to go into REDCap and manually re-save/ re-submit?

**Comment by DESm1th** [comment]
If you want it to appear in the dashboard, yes. :( The only time the dashboard updates its redcap information is when the data entry trigger fires. It's not doing any scraping of existing data to make sure redcap records havent been missed. New scan completed forms will be fine though.

**Comment by navonacalarco** [comment]
Alright, got it! Thanks.
