### ISSUE TITLE
PRELAPSE IWA DTI not comming down from XNAT

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#1325]
I don't know if this is a real issue or three coincidences...

sessions with DTI in 
PRE01_IWA_R04014_02
PRE01_IWA_R04013_02 
PRE01_IWA_04013_02 

In both cases, 
1) there was a record in the dashboard but not a nii file on the system
2) the Series Description has parenteses 'Ax DTI (60 Direction) 5-B0'

**Comment by josephdviviano** [comment]
@edickie did you try converting to `nii` like we discussed

**Comment by josephdviviano** [comment]
Just confirmed that the data do convert so it must be a REGEX problem or related.

**Comment by DESm1th** [comment]
This was a result of the parentheses in the series description. It was causing the 'mv' command after conversion to nifti to fail. I've fixed it and added logging so that it won't fail silently in the future. You can view the changes here: https://github.com/TIGRLab/datman/commit/866938234abe743605adbe62be5dd354975c87a6
