### ISSUE TITLE
PASAD: question about timepoint naming

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1366]
Hi guys,

One more question about PASAD:

Neda and I noticed that it seems to be that the 'timepoint'  information looks a bit off. The study should contain data from a single timepoint, but the MRS files are (mostly) indicated as being from an '02' timepoint (despite being collected on the same date). Here's an example:

Feb  6  2017 PASAD_CMH_TF26H001_01_01.zip -> ../zips/2013_0702_TF003.zip
Feb  6  2017 PASAD_CMH_TF26H001_02_01.zip -> ../zips/20130702_Ex01475_PASA1MR_MRSROI.zip

There's also a few examples where the MRS data is indicated as from the '01' timepoint, and the remaining acquisitions are indicated as '02'.

Feb  6  2017 PASAD_CMH_GL26A030_01_01.zip -> ../zips/20150604_Ex03864_PASA1MR_MRSROI.zip
Feb  6  2017 PASAD_CMH_GL26A030_02_01.zip -> ../zips/2015_0604_GL027.zip

I think I remember that Dawson was working on retroactively 'recovering' this study's data, in February. Just wanted to check in to see if there's a reason for this naming convention, and/or if it should be corrected.

**Comment by DESm1th** [comment]
I think Dawson had written a script to automatically name these (I could be mistaken) so it might be that something went wrong there. I'll look into it.

**Comment by DESm1th** [comment]
Ok, so it looks like a few things went wrong here. 

1. According to this issue https://github.com/TIGRLab/admin/issues/1059 Nancy said we shouldn't be using the _MRSROI files. 'Ignore' was added for each entry in the scans.csv but seems that no one deleted the named links so they've lingered despite, apparently, being garbage

2. Dawson's script to generate the scans.csv bungled the timepoint stuff a bit. When two scans mapped to the same name and had the same date/time, whichever one was found first got labeled _01 and the other got _02. Which is why sometimes those MRS files are _01. 

So if this data really is all just a single time point than what I think needs to be done is we'll have to correct the scans.csv file to make sure that all the _MRSROI files are really being ignored, update it to ensure the 'real' data zips are always given the _01 timepoint, and then purge everything so things regenerate with the correct names.

Does this sound ok? Did I miss / misunderstand anything?

**Comment by navonacalarco** [comment]
That makes a lot of sense to me! Please let me know what I can help with. Thanks, Dawn.

**Comment by DESm1th** [comment]
I renamed these on Friday, and purged all the old outputs. @navona said she'll take a look to make sure everything looks correct now, and then we can close the issue

**Comment by navonacalarco** [comment]
Looks perfect, Dawn. Thank you.
