### ISSUE TITLE
PACTMD: multiple files for SPRL (for early scans)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#1367]
For early PACTMD scans (acquisition predating the Dashboard), it looks like the single SPRL scan is being interpreted by the Dashboard as 4 or sometimes 5 independent scans.

For example, the QC page for PACTMD_CMH_0100001_01 indicates 4 SPRL scans were collected (all as session '0')

Another example, the QC page PACTMD_CMH_0100017_01 indicates 5 SPRL scans were collected (1 as session '0', and 4 as session '4').

I didn't track down exactly when this stopped, but new scans coming in do not have this issue.

As far as I can tell, in all cases, there's a single SPRL acquired; not sure why the Dashboard is variably interpreting the number of file and the acquisition number.

It seems that the visual displays on the QC page are all identical. This means we can QC. But, thought it was worth raising this as an issue to get others' thoughts / see if it's indicative of any kind of problem.

**Comment by DESm1th** [comment]
Hey Navona. This isnt actually a dashboard issue, or a bug really. At some point in the past I think either as a result of the dm_xnat_extract resources bugs, or as a result of some bug with our spiral linking script, we ended up with multiple links/copies of the same spiral scan with slight name variations. QC report generated metrics for each of these and they show in the dashboard because no one deleted them. 

They all represent the same data though, and it can be fixed by deleting the duplicates from the nii folder (if they still exist), clearing out the qc folder for the subject, and then rerunning dm_qc_report.py

**Comment by navonacalarco** [comment]
Thanks Dawn! Looks like for most/all, the duplicates have been removed from data/nii and qc. I'll rerun the QC pages.
