### ISSUE TITLE
CIVET jobs don't run on the queue, or fail because of the modules system

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#178]
I think you guys already know this but just in case... When trying to run CIVET, 1) I come across a permissions issue, 2) the analysis doesn't seem to be running on the q, and 3) The VBM smoothing step fails. These aren't critical because we're still able to run CIVET and get the thickness data, but it might be good to make a note of it in case someone wants VBM.

**Comment by pipitone** [comment]
Okay: 

- the `CIVET-1.1.10+Ubuntu_12.04` module should now submit to the queue
- the `CIVET-1.1.12` should also submit to the queue, and I see no problems so far with it... but let me know. 
- the `CIVET-1.1.10` module is not operational, and I'm having a lot of trouble compiling it for our version of Ubuntu. I will have to speak with Gabe from the CIC about this. For the moment, I've disabled the module so that no one will accidentally try to use it. 

Let me know how it goes.

**Comment by mlevesque82** [comment]
Will do thanks!

**Comment by pipitone** [comment]
Okay, just sat down with Melissa and confirmed that `CIVET-1.1.10+Ubuntu_12.04` does now submit jobs to the queue, but.... jobs fail immediately, I think, because of an interaction with the `modules` system. The log for the job shows the output from `module` as if it was called without arguments, e.g. 

```sh
cmdModule.c(166):ERROR:11: Usage is 'module command  [arguments ...] '

  Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]
```
and then, I think, the job just stops. I haven't looked too deeply into this to be sure about what actually is happening, except to say that if you run `unset module` (which undefines the `module` function), and then run `CIVET_Processing_Pipeline` the jobs both get submitted and run to completion. 

I'm leaving this ticket open until we fix this particular problem.

**Comment by pipitone** [comment]
This clearly isn't a thing any longer. Reopen if necessary.
