### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#220]
I currently don't have permissions to look at or copy anything in archive/data-2.0/OBI_POND and I need to analyse those data for Stephanie. I also don't have permission to give myself permission using chmod 777 *. Could I be granted permission please? Thanks!

**Comment by josephdviviano** [comment]
Hey Melissa,

+ You should be able to view them now.
+ A tip for future reference: a better way of safely giving everyone permission to open/view files and folders is chmod -R ugo+rX (capital X). This is because 777 gives world-access to everything, including delete permissions, AND makes all of the text files executable, which means someone else could write something silly (say "rm -rf *") in one of them, and then when that text files gets executed, maybe all of your datas will be gone :(
