### ISSUE TITLE
RTMSWM_CMH_WM040 has not been added to metadata/checklist.csv

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#247]
All scans should be added to the `metadata/checklist.csv` file automatically by the qc script, but here's one that hasn't been. This may point to a larger problem with the qc code. Worth having a look. 

```
jp@tigrsrv:/archive/data-2.0/RTMSWM$ grep WM040 metadata/checklist.csv                                                                 
jp@tigrsrv:/archive/data-2.0/RTMSWM$ ls data/nii/RTMSWM_CMH_WM040_01/
RTMSWM_CMH_WM040_01_01_DTI33-1000_12_Ax-DTI-33plus2-b1000.bval  
RTMSWM_CMH_WM040_01_01_DTI33-4500_10_Ax-DTI-33plus2-b4500.nii.gz
...
```

**Comment by josephdviviano** [comment]
Yes it turns out something I added to the QC script RE the single-subject sqlite database broke the thing pretty early (actually, I just changed the command-line argument structure and then didn't updated the run.sh scripts) -- so that script has been regularly failing. I've fixed that now, and updated all of the run.sh scripts.

+ I really should make the command line argument for the single subject database mandatory so this sort of thing can't happen again.
