### ISSUE TITLE
turn on auto-updating for all machines in the lab?

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#256]
@pipitone @edickie 

I'm thinking it might be good to put a very simple root-owned cronjob in the system that would auto apt-get update / upgrade every night. This would keep everything in sync (right now I'm noticing some pretty major differences in update frequency between workstations).

What do you think? Objections or praise?

**Comment by pipitone** [comment]
-1, mostly.

First off, Ubuntu has a built-in mechanism for unattended upgrades (it's called 'unattended-upgrades'), so let's use that.  

But, I'm wary of forcing (nightly) full upgrades without proper testing just to be sure that upgrades don't break important things. 

That said, unattended-upgrades has the option to only install security fixes, which, if we aren't doing this already, should probably be done.  I'm certainly +1 to that. 

Perhaps check what the cobralab is doing (github.com/cobralab/ansible-playbooks) because I do trust Gabe to have made a wise decision on this matter.

**Comment by josephdviviano** [comment]
Yes I'm aware of unattended-upgrades, but I'm talking about doing full upgrades.

**Comment by josephdviviano** [comment]
Gabe hasn't done this. OK. I'll ditch the idea.
