### ISSUE TITLE
Incomplete RESOURCES folder for RTMSWM

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#282]
_From @pipitone on May 28, 2015 20:26_

Similar to #41, the RTMSWM data folder is missing non-dicom RESOURCES exported from XNAT. Plan: 

- [x] Delete all RTMSWM data from XNAT
- [x] Run `dm-xnat-upload.py` to reupload all of the scan data to XNAT, and run `dm-xnat-extract` to verify all scan data has been extracted properly.
- [x] Update the RTMSWM README Changelog to say this happened and reference this ticket. 
- [x] `git commit -am`

_Copied from original issue: TIGRLab/data#42_

**Comment by pipitone** [comment]
This issue is still outstanding. All subjects earlier than `RTMSWM_CMH_WM039_01_01` do not have resources data exported. 

I checked, and the earlier scans have `txt` and `pdf` files in the source zip files: 

    for i in data/dicom/*.zip; do echo $i $(unzip -l $i | grep -i 'txt\|pdf'); done

But neither these files (nor the `RESOURCES` folder) exist in `tigrsrv:/mnt/xnat/spred/archive/RTMSWM/arc001/*' folders.

**Comment by josephdviviano** [comment]
I'm deleting these `bros` now.

**Comment by josephdviviano** [comment]
Correction... just did it now.

FYI, don't try to delete a lot of data through the web GUI. It is much faster to `ssh` into `srv-web` and then `rm` the `.dcm`s from `arc001` in a given project folder, and THEN use the GUI to clear out the associated entries in the database. Otherwise it is very likely your session will timeout during the deletion.

I'm guessing the run script will re-upload everything tomorrow morning, and then I can close this issue.

**Comment by josephdviviano** [comment]
Looks like the files are being uploaded. @pipitone @edickie , the run script is going to take a long time this morning because RTMSWM is re-uploading the entire project. I'll close this issue after the upload completes.

**Comment by pipitone** [comment]
Thanks broseph. You're on a roll!

**Comment by josephdviviano** [comment]
OK, looks like everything is done.

I'm not updating the README because that is just going to be confusing to people in the future, the data versions are all identical (with more of the left-out stuff now available).
