### ISSUE TITLE
mansfield is eating jobs

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#304]
mrsdti kills jobs because jobs are 'not supposed to be there on mansfield'

from the exed logs on mansfield: `/var/spool/gridengine/execd/mansfield/messages`

    09/11/2015 17:29:31|  main|mansfield|W|can't read pid from pid file "active_jobs/193295.1/pid" of shepherd for job active_jobs/193295.1

**Comment by pipitone** [comment]
I'm not sure what you mean by "jobs are 'not supposed to be there on mansfield'".

It looks like `gridengine-exec` got wedged after job 193295 failed to run. I shutdown the daemon, removed `/var/spool/gridengine/execd/mansfield/active_jobs/193295` because that job was long gone, and restarted the execd daemon. All good.
