### ISSUE TITLE
<ignore> marker on scan.csv not getting ignored..

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#332]
I've adding <ignore> to scan.csv to silence these three errors, but they keep coming back!

ERROR: /archive/data-2.0/COGBDO/data/zips/_processed.zip: Contains no DICOMs. Skipping.
ERROR: /archive/data-2.0/COGBDY/data/zips/2014_0314_AM010_DicomMissing.zip: Contains no DICOMs. Skipping.
ERROR: /archive/data-2.0/RTMSWM/data/zips/2011_Marker_TestScanData_RTMS1MR.zip: Cannot find scan id. Skipping

**Comment by pipitone** [comment]
The `Contains no DICOMs` case is interesting since the `link.py` script aborts with an error without DICOMs before checking the `scans.csv` file (since the check in `scans.csv` is typically followed by a validation that all of the dicom header fields match). 

I'm going to rejig things so that if a file contains no DICOMs, then it's skipped quietly by `link.py`.
