### ISSUE TITLE
main.q can't find the shared libraries used by `ls`.

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#338]
ls: error while loading shared libraries: libpcre.so.3: failed to map segment from shared object: Cannot allocate memory

Of course, these commands run fine when not run on the queue.

**Comment by pipitone** [comment]
This isn't a problem with finding the library, but getting the memory to load it: 
http://serverfault.com/questions/710264/failed-to-map-segment-from-shared-object-cannot-allocate-memory

Not sure what's going on here exactly.

**Comment by pipitone** [comment]
Think I found it. I had turned on `h_vmem` (the hard memory limit SGE imposes on running jobs) to stop Arash's jobs from overwhelming the workstations, but I hadn't changed the default. This wasn't a problem for Arash since he was requesting a specific value, but was causing jobs that didn't request `h_vmem` to fail. 

I've set `h_vmem` default to `4G` (via `qconf -mc`).
