### ISSUE TITLE
data-2.0: multiple repeats for T1 files and inconsistent uppercase/losercase

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#357]
Hi guys,

In some instances the T1 images have been repeated due to patient motion. Generally speaking the first T1-BRAVO image has an issue. I was wondering if you could rename/move the repeat with motion artifact and keep the correct one as is. 

Here are the directories with multiple repeats of T1 repeats along with the image name with less motion artifacts that should be kept as is:

#DTI Sample:

**DTI_CMH_H037_02:**
DTI_CMH_H037_02_01_T1_18_Sag-T1-BRAVO.nii.gz 

**DTI_CMH_S142_01:**
DTI_CMH_S142_01_01_T1_11_Sag-T1-BRAVO.nii.gz

#COGBDY:
**COGBDY_CMH_27B034_01:**
Both images seem fine. I guess one of them should be picked randomly or second one if we are to think they saw something that we can't see.

**COGBDY_CMH_27B036_01:**
Both images seem fine. I guess one of them should be picked randomly or second one if we are to think they saw something that we can't see.

Here are the images with inconsistent naming (BRAVO is Bravo in these folders):
**COGBDY_CMH_27B040_01** **COGBDY_CMH_27B041_01** **COGBDY_CMH_27B042_01:**

**Comment by josephdviviano** [comment]
Hi Arash, we can remove 

     DTI_CMH_H037_02_01_T1_18_Sag-T1-BRAVO.nii.gz 
     DTI_CMH_S142_01_01_T1_11_Sag-T1-BRAVO.nii.gz

If they have artefacts, but what is the problem with having two good T1 scans? You could average them, for example. Also the inconsistent naming is actually from the DICOM header and won't be fixed. You can easily script around this.

**Comment by arash-n** [comment]
These two are fine:
 DTI_CMH_H037_02_01_T1_18_Sag-T1-BRAVO.nii.gz 
 DTI_CMH_S142_01_01_T1_11_Sag-T1-BRAVO.nii.gz

These two have problems:
DTI_CMH_H037_02_01_T1_02_Sag-T1-BRAVO.nii.gz
DTI_CMH_S142_01_01_T1_04_Sag-T1-BRAVO.nii.gz

Nothing is wrong about either of those. I thought it will make copy/pasting easier. That's all.

**Comment by josephdviviano** [comment]
OK we will blacklist 

    DTI_CMH_H037_02_01_T1_02_Sag-T1-BRAVO.nii.gz
    DTI_CMH_S142_01_01_T1_04_Sag-T1-BRAVO.nii.gz

but leave the rest as-is. If you see other corrupted scans that should be blacklisted, please let us know.

**Comment by arash-n** [comment]
Sure! ;)

**Comment by pipitone** [comment]
@arash-n wrt the inconsistent naming, we take the description directly from the DICOM headers as it is, so this inconsistency is coming from the scanner/scan techs. We could try to normalise the description field, but I think we'd be in for a world of pain because of how unpredictable it is. Instead, we *always* have a `_T1_` in the name of the file if it's a T1, and a `_DTI` if it's a DTI, etc.. These "tags", as we call them, are what you should rely on for consistency and to tell you the kind of scan the data came from.

**Comment by arash-n** [comment]
You are right, that makes sense. I was thinking of running a simple code like this:

`<addr>`for f in * ; do mv -- "$f" "$(tr [:lower:] [:upper:] <<< "$f")" ; done

**Comment by pipitone** [comment]
> You are right, that makes sense. I was thinking of running a simple code like this:
> 
> `<addr>`for f in * ; do mv -- "$f" "$(tr [:lower:] [:upper:] <<< "$f")" ; done

Sure, you're welcome to do it on your own copies/links of the files. ;-)
I don't think it's the right way for us to go since soon enough someone
will ask, "can you make the 'SAG-T1-BRAVO' and 'SAGT1-BRAVO' and
'BRAVO-SAG-T1' files all say 'SAG-T1-BRAVO'?"

That is, unless there's a strong reason you need to have the description
normalized.

**Comment by josephdviviano** [comment]
RE:

    DTI_CMH_H037_02_01_T1_02_Sag-T1-BRAVO.nii.gz
    DTI_CMH_S142_01_01_T1_04_Sag-T1-BRAVO.nii.gz

I've removed the aformentioned exported niftis, freesurfer runs, and their nifti exports, as well as adding them to he blacklist.csv file. I'm also deleting the functional runs, as they depend on the anatomical data. Everything should regenerate tonight.
