### ISSUE TITLE
VIPR1 MRI (Foussias)

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#396]

**Comment by Navona-Calarco** [comment]
Can we please pull the MRI data for Dr. Foussia's study (VIPR1MR) into ric?

**Comment by josephdviviano** [comment]
Hi Navona,

We're currently storing the VIPR1MR study into 'VRMD' `data-2.0`:

    /archive/data-2.0/VRMD/data/nii

Have a look here -- does it appear like we have all of the subjects?

**Comment by Navona-Calarco** [comment]
@josephdviviano wrong one :'((((

**Comment by josephdviviano** [comment]
Hey @Navona-Calarco  you should be able to assign etc. now.

**Comment by josephdviviano** [comment]
More clearly: @pipitone @edickie,

We've been asked to monitor an additional study: VIPR1MR. This means we need to:

- [ ] Set up passwordless access to the MR server for VIPR1MR
- [ ] Make the appropriate folders and files for this in `/archive/data-2.0`
- [ ] Set up a `run.sh` script for this study
- [ ] Reference this script in the master `run.sh` script so it is run nightly.

I'm going to assign this to @edickie so that she can learn how to set up one of these studies from scratch.

**Comment by Navona-Calarco** [comment]
Thanks all!

**Comment by pipitone** [comment]
@edickie, let me know when you're getting started on this. I'll need to install `clevis`'s ssh key on the MR FTP server. 

Actually, this is something we should discuss further at some point, since it's not absolutely necessary and cumbersome since it relies on me having admin access to the server (or getting Nancy et al. to do it for us). We could just store the user/pass in a file, like we do with the XNAT credentials.

**Comment by josephdviviano** [comment]
@edickie probing you to see how this is going -- due to the 'spiral artefact' débâcle, it would be good to run these resting-state data through datman.

**Comment by edickie** [comment]
This is mostly set up.. Scans for the first subject are in all transfered. I'm going to check this again after talking to navona about some protocol stuff than set up the gold standards on Monday

**Comment by josephdviviano** [comment]
@edickie where are we at with this?

**Comment by edickie** [comment]
Pretty much done.. All the task-spirals are transfered if @josephdviviano wants to activate a pipeline for them...

We have two issues:
1) the connection to the PET is not working inside the run script (I re-opened issue #397)
2) the PDT2 file is not splitting...(dm-proc-split-pdt2.py keeps exiting with errors)

**Comment by edickie** [comment]
PDT2 issue is solved..closing this..

**Comment by navonacalarco** [comment]
Hey guys,

Can I just confirm - once more - that running these resting-state data through datman resolved the 'spiral artefact' débâcle?

In meeting with GF and he asked for confirmation.

Thanks!

**Comment by josephdviviano** [comment]
Hey @navonacalarco , no evidence so far that these artifacts are anything to worry about.
