### ISSUE TITLE
No module system on Laplace

### ISSUE THREAD

**Issue by 7jw9** [TIGRLab/admin#405]
Wahhhh.

**Comment by josephdviviano** [comment]
Hi Julie,

Is this still a problem? I can see module through `ssh`, but I **was** having trouble with module before on `mrsdti`. It seems to be working now (again, through `ssh`).

**Comment by josephdviviano** [comment]
@7jw9 :D

**Comment by 7jw9** [comment]
Yeah, @josephdviviano, still not working. Also, Amy's using that computer right now, and she can't load modules either.

**Comment by josephdviviano** [comment]
@7jw9 confirmed. module works for my user `jdv`, but not `julie`. So profile.d isn't being sourced by all users.

**Comment by 7jw9** [comment]
Kewl

**Comment by josephdviviano** [comment]
@pipitone , I'm pretty sure we need to tell machines to look at `profile.d` for non-login shells. On most of the machines I'm looking at, they have

```
source /etc/profile.d/modules.sh
source /etc/profile.d/quarantine.sh
```

in `/etc/bash.bashrc`.

According to [this](http://askubuntu.com/questions/438150/scripts-in-etc-profile-d-being-ignored), `profile.d` will only be sourced in login shells unless it is referenced in `bash.bashrc`, `~/.bashrc`, or similar.

**Comment by josephdviviano** [comment]
ps @7jw9 and Amy: 

As an interm fix, just put these lines in your ~/.bashrc:

```
source /etc/profile.d/modules.sh
source /etc/profile.d/quarantine.sh
```

**Comment by pipitone** [comment]
@josephdviviano Yeah, it looks like you're right about `/etc/bash.bashrc` being necessary for X11 terminals. I had thought `/etc/profile` was read when `lightdm` starts up, but apparently not. I suspect `gdm` and other display managers might read `/etc/profile` (since it's supposed to be for login shells...). 

In any case, I added the `source` lines to `/etc/bash.bashrc` in our 'quarantine' role in tigrlab/ansible-playbooks@f52f1f0 so we should all be good now.
