### ISSUE TITLE
shared files for SPN_01_CMH_0046 / VIPR_AA2101

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#406]
This is related to the _VIPR1 MRI (Foussias)_ ticket, but I thought different enough for a new issue.

Tomorrow, there's a participant being scanned for both SPINS and VIPR. Because there are shared acquisitions between studies, T2 Flair and DTI will be dropped from the ViPR scan.

However, the T2 Flair and DTI files will need to be added to the `/archive/data-2.0` folder that will be set up for ViPR.

The participant's SPIN ID is SPN_01_CMH_0046 and VIPR ID is AA2101.

**Comment by josephdviviano** [comment]
Do we really need to do this? We can just maintain a file somewhere that records that these participants are the same person. @pipitone @edickie  what do you think?

**Comment by edickie** [comment]
I think we need to do both...

1) copy (or link?) the files between the two projects so that processing
pipelines can access all the files it needs easily
2) create a file somewhere that keeps track of shared subjects

**Comment by josephdviviano** [comment]
@edickie , the reason I'm sceptical about the linking is because we'd essentially be processing the same data twice, and storing the outputs twice. We could also link the outputs, but that could get complicated. Also, if we do this and people aren't careful, they might think these linked copies of the data are novel scans (i.e., two different DTI scans on the same person) or even worse, two different DTI scans on two different people.

**Comment by edickie** [comment]
@jdv,
1) I think we should link only the raw files (not the outputs) because
different projects might have versions of analysis software run on them...
2) Your concern these being interpreted as two different poeple is already
happenning. We create a more systematic to keep track of shared
participants to deal with this...

**Comment by josephdviviano** [comment]
@edickie 

1) is a good point.
2) Agreed about a systematic method.

@pipitone and I talked about maintaining a tracking file (like `scans.csv`, but for all projects at once), in which each line represents a single unique human, and each column represents a session for that person (something like this ... we could flip columns and rows if you would prefer):
```
SPN01_CMH_0001  DTI_CMH_0034 DTI_TGH_0078
SPN01_CMH_0002
SPN01_CMH_0003 PRE05_CMH_0044
```

On second thought, we could also have a file in each project that maps `DCM` data to another target study. So the **from** study would contain a file called `external-links.csv` and could contain:

```
subject         target_project target_subject
SPN_01_CMH_0046 VIPR           AA2101 
```

This might be less work overall because we'd only need to explicitly define the subjects that need mapping.

Also, in this system, we could just link all of the raw NIFTI files over to the other subject. The filenames themselves would denote that they originated from another study.

**Comment by edickie** [comment]
I like option 2. Separate files in each project's metadata folder because:
1) there's an obvious place for us (as clevis) to look for the file
2) easier for version control
3) when somebody is combining data across multiple projects they can
concatenate each projects' external-links.csv files together (instead of
parsing the big file from option 1)

**Comment by edickie** [comment]
@navonacalarco just setting this up... Can you clarify which are to be linked?
We have a scan for AN2101...but this subject has T2 and DTI scans already.

Also, is there supposed to be Spiral scans in this protocol?? We didn't get any from AN201

**Comment by edickie** [comment]
wait sorry - there's a ton of spirals...I see them now

**Comment by navonacalarco** [comment]
@edickie The DTI and T2 flair acquisitions for SPN_01_CMH_0046 need to be copied into VIPR_AA2101 (same participant, scanned same day for both SPINS and ViPR; the DTI and T2 were dropped from ViPR as they were already done for SPINS).

If there's already DTI and T2 scans there, perhaps that was something that the Imaging Centre (tech: Gary) did for us? He didn't mention doing so, though, so could you please double check?

Thanks!

**Comment by edickie** [comment]
links added to VIPR/data/nii/VIPR_CMH_AA2102_01
lrwxrwxrwx 1 clevis clevis      111 Feb  9 15:30 VIPR_CMH_AA2102_01_01_DTI60-1000_16_Ax-DTI-60plus5-20iso.bval -> /archive/data-2.0/SPINS/data/nii/SPN01_CMH_0046_01/SPN01_CMH_0046_01_01_DTI60-1000_16_Ax-DTI-60plus5-20iso.bval
lrwxrwxrwx 1 clevis clevis      111 Feb  9 15:30 VIPR_CMH_AA2102_01_01_DTI60-1000_16_Ax-DTI-60plus5-20iso.bvec -> /archive/data-2.0/SPINS/data/nii/SPN01_CMH_0046_01/SPN01_CMH_0046_01_01_DTI60-1000_16_Ax-DTI-60plus5-20iso.bvec
lrwxrwxrwx 1 clevis clevis      113 Feb  9 15:29 VIPR_CMH_AA2102_01_01_DTI60-1000_16_Ax-DTI-60plus5-20iso.nii.gz -> /archive/data-2.0/SPINS/data/nii/SPN01_CMH_0046_01/SPN01_CMH_0046_01_01_DTI60-1000_16_Ax-DTI-60plus5-20iso.nii.gz
lrwxrwxrwx 1 clevis clevis      100 Feb  9 15:34 VIPR_CMH_AA2102_01_01_PD_17_OblAxT2-DEfseXL.nii.gz -> /archive/data-2.0/SPINS/data/nii/SPN01_CMH_0046_01
/SPN01_CMH_0046_01_01_PD_17_OblAxT2-DEfseXL.nii.gz
lrwxrwxrwx 1 clevis clevis      102 Feb  9 15:33 VIPR_CMH_AA2102_01_01_PDT2_17_OblAxT2-DEfseXL.nii.gz -> /archive/data-2.0/SPINS/data/nii/SPN01_CMH_0046_01/SPN01_CMH_0046_01_01_PDT2_17_OblAxT2-DEfseXL.nii.gz
lrwxrwxrwx 1 clevis clevis      100 Feb  9 15:34 VIPR_CMH_AA2102_01_01_T2_17_OblAxT2-DEfseXL.nii.gz -> /archive/data-2.0/SPINS/data/nii/SPN01_CMH_0046_01/SPN01_CMH_0046_01_01_T2_17_OblAxT2-DEfseXL.nii.gz

nrrd file for DTI also linked

There is a file external-links.csv with
subject                                     target_subject
SPN01_CMH_0046_01_01     VIPR_CMH_AA2102_01_01

All note that linked files have the id  VIPR_CMH_AA2102_01_01 all files from the newer (VIPR) session have the id  VIPR_CMH_AA2102_01_02
