### ISSUE TITLE
COGBDY/COGBDO

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#412]
Hi Guys,

Does anyone know if there is an uptodate log file including the basic demographics of COGBDY/COGBDO subjects (age, sex, and handedness)?

Cheers,
Arash

**Comment by josephdviviano** [comment]
Hey @navonacalarco  ... would you know how to check this?

@arash-n -- if there aren't demographic data in data-2.0 (did you check?) I'm at a loss.

**Comment by arash-n** [comment]
There are  excel sheets that was relatively out of date at: 
/archive/data-2.0/COGBDY/metadata/raw/

/archive/data-2.0/COGBDO/metadata/raw/

**Comment by arash-n** [comment]
I basically need the age/sex of these subjects:

B036, B039, B040, B041, B042, B044

**Comment by navonacalarco** [comment]
@arash-n 

I'm at QS right now; I asked the COGBD RA and she's pulling it.

**Comment by navonacalarco** [comment]
@arash-n I set you an email with the data! :)

For next time, I was told to tell you we have to fill out a Data Request form (I'll try to find a copy) and email it to the GMHP manager, Lillian. This is the case because this study is being managed by Geriatrics, not Kimel/ Slaight.

I believe Melissa and Laura have done this before, so they could tell us more about how that works and what the timeline is (also, Melissa and Laura might have more up-to-date data that they haven't put in data 2.0).

I do know that data requests for COGBD are taking a long time at the moment in large part because they're using a dysfunctional database. I'm here now because we're setting up a new one. They also just hired a COGBD RA, and have a months-log backlog of data entry. 

As we set up the new database, I'm going to advocate for a 'pull-data only' REDCap account for the TIGRlab so that we can access this data directly in the future.
