### ISSUE TITLE
Set up SFTP server on Kimsrv

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#430]
We need some way of getting the PACTMD DICOMS from #426 out to the rest of the world.

According to @pipitone, the CAMH SFTP service is upload only. Therefore we will need our own so people can download our (password protected) DICOM files.

**Comment by pipitone** [comment]
Before I set this up I'll need a few more details: which users will need access to this? Is it SFTP absolutely or are they fine with SSH/SCP access? 

Alternative idea: can we instead give them an XNAT user account and have them download the zip files directly through XNAT (either by using the default XNAT zip download where they can select the series they are interested in, or by posting up custom zips into the RESOURCES folder)?

**Comment by navonacalarco** [comment]
Hi guys,

I don't know anything about this officially, but I was in a meeting the other day when this issue was discussed (I think). It sounded like, for PACTMD, Dr. Rajji needs to send T1 and T2 scans to the participant's respective physicians. He asked Lillian Lourenco, the Geriatrics manager, to look into getting this set up. As Kimel is managing PACTMD's data, I gave her @josephdviviano and @pipitone 's email addresses. She plans to get an RA to pull the T1 and T2s, and send to the physicians as the scans come in.

**Comment by pipitone** [comment]
Thanks Navona. 

Looks like we will go the XNAT route then, and perhaps make some
instructional videos to help people navigate XNAT and download.
