### ISSUE TITLE
Combine /archive/data with /archive/data-2.0

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#445]
We have a duplicate of much of our raw data in `/archive/data` and I think it's time we get rid of it. This task is mostly a matter of `rm -rf`, but I think its worth checking before this to make sure we aren't getting rid of anything in `/data` that's missing from `/archive/data-2.0`.

**Comment by pipitone** [comment]
There is also the stuff in `/projects/DT_study` that should be merged into `/archive/data-2.0/DTI/TGH`. I may need @dfelsky's help with that bit.

**Comment by pipitone** [comment]
Here are the folders in /archive/data we need to merge. I will update this comment as I inspect them (see /projects/jp/data-merge): 

- [ ] **COGBD** - Only a handful of .add and three .dcm files differ. Assuming we have the originals.
- [ ]  **DT_sample**
- [ ] **Hillside**
- [ ]  **MATT_DATA_archive**
- [ ]  **ML_Group**
- [ ]  **models**
- [ ]  **MULTISITE**
- [ ]  **N107**
- [ ]  **NY_Group**
- [ ]  **PPMI**
- [ ]  **processed**
- [ ]  **rTMS**
- [ ]  **SEGMENTATIONS**
- [ ]  **STOP_PD_II**
- [ ]  **tcp**

**Comment by josephdviviano** [comment]
@pipitone this seems like an important thing for you to finish before you go. likely the most important. where are you with this?

**Comment by pipitone** [comment]
I won't be able to finish this before I go, and honestly I'm no better
at it than anyone else because it simply involves looking at the files
in /archive/data and determining if they are already in
/archive/data-2.0 or not.

I've gone through several of the projects and reconciled them with
/archive/data-2.0 projects: found anything missing and copied it over to
data-2.0 (there was very little of that actually), and then deleted the
project from /archive/data. So, any projects remaining in /archive/data
are left to sort out. 

My approach has been quite laborious, but it's this: 

1. For dicoms: inspect every  single dicom file in a /archive/data/
project folder, and generate a sha hash for it, and then compare that to
hashes for all the files in all of the zips in the corresponding
/archive/data-2.0 project. Most of them map, but the ones that are
missing need to be inspected carefully. Unfortunately, there are some
dicom files with different hashes but identical headers so for those
I've just been using what we have in data-2.0 since we have the
originals from the MR unit. 

2. For non-dicoms I've mostly been ignoring any nii files because we
have converted versions now. I've also been jettisoning distortion
corrected images and other preprocessed work because we can regenerate
that from a David scripts if we need to. Anything else remaining that
looks important (scan notes, etc..) I've stuck in the docs/ metadata/ or
RESOURCES/ folders (again, there hasn't been much of this).

**Comment by josephdviviano** [comment]
Remaining:

+ Hillside
+ MATT_DATA_archive
+ ML_Group
+ MULTISITE
+ N107
+ NY_Group
+ pbsweb
+ perl5

**Comment by josephdviviano** [comment]
Multisite notes:


Hey Erin,

Here's what I was able to disentangle from this data set. I couldn't identify ML, ML_DEC, and Repository/ML_Copy/, because there doesn't seem to be a consistent enough naming scheme to say for sure which data belongs to which person without the headers (the subject numbering changes arbitrarily sometimes so folder names are no help).

Participant 'SP':
  - NY/Subj1-Ex14448Se07
  - NY_DEC/SP_renamedZ
  - Repository/2012_0910_001SP
  - Repository/NY_RAW/NY/renamedZ_A1
  - Repository/subject1
  - TO/TO/2012_0910_001SP

Participant 'JW':
  - NY/Subj2-Ex14452Se10
  - NY_DEC/JW_renamedZ
  - Repository/2012_0910_004JW
  - Repository/NY_RAW/NY/renamedZ_A2
  - TO/Original_Setup/subject3
  - TO/TO/2012_0910_004JW

Participant 'JK':
  - NY/Subj3
  - NY_DEC/JK_renamedZ
  - MAYBE : Repository/NY_RAW/NY/sorted_A3
  - Repository/subject4
  - TO/TO/JK700

Participant 'DB':
  - NY/Subj4-Ex14456Se09
  - NY_DEC/DB_renamedZ
  - Repository/2012_0910_003DB
  - Repository/NY_MISSING
  - Repository/NY_RAW/NY/renamedZ_A4
  - Repository/subject5
  - TO/Original_Setup/subject2
  - TO/TO/2012_0910_003DB
  - TO_SUB3_T1

Participant 'CM':
  - NY/Subj5-Ex14457Se09
  - NY_DEC/CM_renamedZ
  - Repository/2012_0910_002CM
  - Repository/NY_RAW/NY/renamedZ_A5
  - TO/TO/2012_0910_002CM


Notes:
  - Repository/2012_0910_005JK actually contains Ex00698 which headers say
    is participant 'DB', but the two folders don't contain identical copies
  - All participants in Pilot also have a folder with the same name in Pilot/PILOT_SCANS
    but S057_CAMH and S061_CAMH are only in Pilot/PILOT_SCANS. Data seems unrelated
    to everything else
  - Repository/subject2 and Repository/subject3 don't have dicoms to check, but
    are probably JW and CM (can't tell which is which though)
  - TO/Original_Setup/subject1, TO/Original_Setup/subject4 and TO/Original_Setup/subject5
    don't contain dicoms to allow identification.

**Comment by josephdviviano** [comment]
+ more on hillside: the first round of scans there were a bust, so they have a re-do set of scans. the first set should be discarded.

**Comment by josephdviviano** [comment]
OK -- 

+ multisite data collected in a new project SPN00 (consisting of the human phantom data -- I've simply saved the names of the DTI pilot subjects since they are already in `DTI/CMH`).
+ Genetic data in 'Hillside' moved to `DTI/CMH/data/genetics/raw`
+ `DTI` has non-raw replication sample data from `MRC` and `ZHH`. I've moved them to `/external/dti-replication-samples` since we can reconstruct the NIFTI data from raw DICOM (if we receive cleaner copies of this data in the future we can replace this).

All done.
