### ISSUE TITLE
merge /projects/david/archive/SCANS into /archive/data-2.0

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#483]
After merging /archive/data (#445), merge in `/projects/david/archive/SCANS`. There is likely nothing of value there once #445 but it can't hurt to look, and it *definitely* will help us on storage (~2.7TiB).

**Comment by josephdviviano** [comment]
It is done.

I found random zip files that looked novel. They've been moved to /archive/data-2.0 but will not nessicarily be mapped into XNAT without some work. I'd consider this a low priority since we've done fine for all these years without the data. It will be much easier to locate the missing stuff in the future.
