### ISSUE TITLE
localadmin can no longer use ansible from tigrsrv

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#505]

**Comment by pipitone** [comment]
Okay, so specifically the issue is that the `init.yml` script doesn't work (each host errors with "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh"). Turns out this is related to Ansible 2.0 (see the [bug report](https://github.com/ansible/ansible/issues/13401), and that the fix is to turn pipelining *on* (in previous versions it had to be off..). This is an interaction between the way we're logging in (without a tty) and using sudo. Joy. The updated command to run the init script is: 

    ANSIBLE_SSH_PIPELINING=y ansible-playbook playbooks/init.yml -kK

I've updated the README.
