### ISSUE TITLE
Should we be using fdt_rotate_bvecs on our eddy_correct'd data? 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#508]
Currently we don't...

**Comment by josephdviviano** [comment]
Where did it come from?

https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1210&L=fsl&D=0&P=441740

**Comment by arash-n** [comment]
I think it is an easy addition to pipeline, now that they have added this to FSL (unlike nrrd to nii conversion problems).

**Comment by josephdviviano** [comment]
From the post above 'You can use it if you want to, but in practice we have not been able to see any differences in our results. '

**Comment by arash-n** [comment]
Maybe. I really can't comment. I just know that everywhere else (but Oxford) they think they should do it.

**Comment by sabashahab** [comment]
See if this helps: http://wiredminds.blogspot.ca/2011/06/dti-preprocessing-in-fsl-b-vector.html

**Comment by pipitone** [comment]
Hmm... Sounds like there is some debate. 

@arash-n, you definitely think we should correct? And `fdt_rotate_bvecs` does the trick well enough, or do you recommend something else?

**Comment by arash-n** [comment]
I would suggest taking a look at the HCP preprocessing to see if they have included that in their pipeline and just follow them. But even if they haven't used it I think it wouldn't do any harm to the data (notwithstanding the effort that should be put in to it to rerun them all over again).
In addition, in the new FSL (I believe 5.0.9) eddy_correct there is a new spline interpolation option. In HCP they use eddy instead of eddy_correct in which spline is the default (rather than trilinear).

@edickie may know it already. If not I'll take a look.

**Comment by arash-n** [comment]
For the second question. I just know that the procedure is rather straightforward and people use their own codes to do it. I may not be able to validate the code easily. Unless we try another code (e.g. camino [which is not gonna do it in nifti]) and compare the rotated bvecs if possible.

**Comment by pipitone** [comment]
Okay, I'm going to close this issue. I've started some documentation on DTI processing over here: https://github.com/TIGRLab/documentation/wiki/DTI-Processing and have included a note about this discussion.

Please add to it.
