### ISSUE TITLE
Can the run scripts run at midnight?

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#551]
Hi guys,

Can we switch the runscript cron job so that they run at midnight instead of 8am..
They seem to take a long long time (todays is still not done) and it would be nice to be able to do all the qc first thing in the morning...

**Comment by josephdviviano** [comment]
I agree --- we could even set them much earlier, say 10 PM.

**Comment by pipitone** [comment]
This has to be coordinated with the MR unit because they need to have their stuff uploaded to the FTP server before we do the pull. Qing will know when that is done by generally. 

Perhaps we can also streamline the run scripts. For instance, right now we do them in serial but we could be running them in parallel at the very least. I think there are also several blocking steps which don't need to block but could instead be backgrounded or submitted to the queue.

**Comment by josephdviviano** [comment]
@pipitone are the steps still blocking? I thought we resolved that ages ago.

Also, we don't have to coordinate with the MR server, if we jump the gun it just means we get the data one day later (there's already a multi day lag because of how the MR server is set up).

**Comment by pipitone** [comment]
Some steps probably do need to block (download/upload, for instance) but there are some steps like qc that block unnecessarily, IIRC. 

I just realized that parallelizing over study run scripts will have to be a bit clever since we have to avoid tripping the MR Unit SFTP rate limiting. Perhaps we can ask for an exception from Qing. 

Also yeah, if we're fine with an extra day of lag then it doesn't matter when we run our stuff. Good point.

**Comment by josephdviviano** [comment]
I think some of the step block unnecessarily, but their outputs are all not time sensitive and, as I recall your effort overhauling the dm-proc-rest pipeline, each script might be a few days of re-working. Do you want to take this on?

As for the rate limiting, we could just stagger the run scripts by a few minutes instead of firing them all off at the exact same time.

**Comment by pipitone** [comment]
Okay, first thing I'm going to do is switch over all of the studies to using passwords for SFTP rather than keys which will make our scripts free of tigrsrv (so also runnable on the S C C)

**Comment by pipitone** [comment]
The run scripts now use sftp passwords.

**Comment by pipitone** [comment]
Okay, I've changed the changed the time the cronjob runs to midnight. As noted, this will mean we may miss some scans that land on the FTP server after midnight.

I'm going to close this issue. There is still work to do to speed up the nightly runs by parallelizing if we need it.
