### ISSUE TITLE
run script error - version?

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#567]
We get the following run-script error repeated for all projects? Does this have to do with the new version checking steps?

/usr/bin/ssh: /opt/quarantine/slicer/4.4.0/build/lib/Slicer-4.4/libcrypto.so.1.0.0: no version information available (required by /usr/bin/ssh)

**Comment by pipitone** [comment]
This is very much an issue with loading the slicer module along with datman, because right now our slicer module puts an old version of libcrypto into the library path. Generally I think we should not be loading processing modules with datman, but instead put them into the run scripts.

That said, let me have a look at the slicer module.. it may be exporting too much anyhow.

**Comment by josephdviviano** [comment]
Yea this is because I added slicer to the database module last night

Joseph's Phone

**Comment by pipitone** [comment]
Nope, if the slicer module is also going to be used to run command line utils, then the module needs to a folder into the library path which includes libcrypto.. so sad.

@jdv, if I remove the module loads you added to the datman.module, what will break?

**Comment by josephdviviano** [comment]
I don't think much important will break go ahead. Just leave in the python
and python extras module

Joseph's Phone

**Comment by pipitone** [comment]
Done.
