### ISSUE TITLE
XNAT autorun pipeline stuck in queued state

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#575]
```
/var/lib/tomcat7/webapps/xnat/logs/application.log
```

Shows

`ERROR org.hibernate.util.JDBCExceptionReporter - ERROR: invalid byte sequence for encoding "UTF8": 0x00`

**Comment by josephdviviano** [comment]
I've probed xnat here: https://groups.google.com/forum/#!topic/xnat_discussion/YnhhAN7P4Ac

**Comment by josephdviviano** [comment]
I've disabled all pipelines and cleared all queued pipelines as an intermediate step, so they shouldn't block operations like moving / renaming data.

**Comment by pipitone** [comment]
XNAT pipeline log files here: `/data/xnat/pipeline/logs`

Lots of useful error logging in there I'm now digging through.

**Comment by josephdviviano** [comment]
@pipitone nice ... missed this one.

**Comment by pipitone** [comment]
You can test pipelines like so from `/data/xnat/pipeline` (see the log file for full command line, which I don't want to post in case it has private info): 

    sudo -u xnat bin/XnatPipelineRunner -config ....

**Comment by pipitone** [comment]
Getting "connection refused" type exceptions. I bet this is because it's not possible to connect via the external IP address from within the box. The external IP is being used in the command line, but when I switch to using `localhost` I get different errors about session management, not connection issues.. Will sort out how to use a domain name rather than IP

**Comment by josephdviviano** [comment]
@pipitone good tip -- 

this line from the logs:

`FATAL main org.nrg.pipeline.client.XNATPipelineLauncher - Couldn't search for queued workflows`

leads me here:

https://groups.google.com/forum/#!topic/xnat_discussion/NiR6fhbjhUk

which suggests that it is a connection issue

**Comment by josephdviviano** [comment]
@pipitone do you mean use domain name within xnat itself?

**Comment by pipitone** [comment]
Yup, or even just the pipeline engine, because then we can map the domain name locally to an accessible IP address (e.g. "localhost").

**Comment by pipitone** [comment]
Success! 

Here's what I did: 
1. Changed the XNAT address via the web interface to `http://xnat.imaging-genetics.camh.ca`
1. Added an entry for this hostname in `/etc/hosts` which points to `127.0.0.1` so that that hostname is accessible from inside the webserver.
1. Changed the routing table so that the webserver could access the RIC network's email server (see the updated netmask for `eth0` in `/etc/network/interfaces`). This wasn't critical but should get rid of all the errors being logged about email server access. 

I'm not able to run the autorun pipeline via the "Build" button (I get a very helpful "unknown error" message and nothing logged in the XNAT or pipeline logs), but when I upload a subject the autorun pipeline does complete successfully (see the subject I uploaded in the "testing" project). 

I'm going to consider this item closed, but create an issue for the custom configuration the webserver needs in `/etc/hosts` to be added to ansible.
