### ISSUE TITLE
Get scc archive/data-2.0 folder to be writable

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#593]
Right now, on the scc, our archive folders are owned user 'nobody' group 'nobody', which means that we can't write pipeline outputs (or anything else) into the archive from an scc node....

Before I email Qing about this again. Who (i.e. what username) are we going to give ownership of archive files to on the scc?? Are we creating a clevis on their system??

**Comment by pipitone** [comment]
We've got an issue about this open over here #588. I've emailed Andy about creating a group, `kimel_admins` which we are all a part of it.

**Comment by pipitone** [comment]
Oops, never mind. This is about our CAMH storage mount. Reopening. :-)

**Comment by pipitone** [comment]
To summarise, there are two issues here: 

1. `nobody` ownerships on the tigrlab SCC mount. This is likely due to the mount being an NFS4 mount but the SCC is not using the IPA nameserver so is getting confused. A remount over NFS3 should do it.

2. Creating a user like our `clevis` for nightly data processing.

**Comment by josephdviviano** [comment]
@pipitone @edickie who is going to implement the remount to nfs3 so we can close this ticker?

**Comment by pipitone** [comment]
Andy. I believe erin has been talking with him about this.

**Comment by edickie** [comment]
Seem to be good
