### ISSUE TITLE
Setup QAP for datman and quarantine

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#642]
According to @edickie, @DESm1th (Dawn) has been working on getting QAP up and running for the POND dataset, but we'd also like to have it generally running in datman and create a quarantine package for it.

FYI, a long while ago I created the  [qap branch of datman](https://github.com/TIGRLab/datman/tree/qap), that has code to make the input files needed for QAP from data-2.0-structured data/folders: https://github.com/TIGRLab/datman/blob/qap/assets/qap-subjectlist.py. Apparently though, newer versions of QAP need more love, says @edickie. 

@DESm1th, maybe you could tell me more about where you're at with running QAP and what you've found out about setting up the latest version?

**Comment by DESm1th** [comment]
Hey Jon,

I've gotten it fully up and running with our POND data and but ran into a lot of trouble along the way. I think most of the difficulty came from not being able to install a lot of the pre-requisites and having to rely on conda environments to get around that (sometimes conda couldn't find packages installed with pip, and so on). 

In order to run it on our system I had to clone their project on git and set it up as a module (for some reason the version installed with "pip install qap" never worked for me), install nitime, nipype, and seaborn. I couldnt get the graph functionality working because it requires graphviz and pygraphviz and I couldn't get one of those installed and working correctly with conda (can't remember which one though). The write_report option appears to produce correct output, except that its outputs seem to go into the working directory which QAP deletes everything from at the end. I didn't try to figure out a fix for this, because Erin said she didn't need those outputs. Erin also mentioned that qap_anatomical_spatial produces incorrect outputs, so we didn't use that either.

QAP also doesn't work for me whenever I try to run more than one subject at a time, or use more than one core per subject. When I try to run 1 subject at a time with multiple cores QAP generates the output directories and pypeline.lock and pypeline.log for each participant but 'finishes' without actually generating any outputs or giving any indication what went wrong. When I try to use one core per subject but more than one subject at once it does the same as above, but also generates a bunch of crash files and gives the following error output for each input: 

Executing node func_get_idx in dir: /projects/dawn/erins-project/QAP_out/func_temporal/wd/MR160-088-0552-01/session_1/func_1/func_get_idx
160726-10:54:50,48 workflow ERROR:
	 ['Node func_get_idx failed to run on host golgi.camhres.ca.']
160726-10:54:50,52 workflow INFO:
	 Saving crash info to /projects/dawn/erins-project/QAP_out/func_temporal/func_temporal_out/parallel_out/crash-20160726-105450-dawn-func_get_idx-4a41fee7-661e-49af-b47b-5df382ae17ce.pklz
160726-10:54:50,55 workflow INFO:
	 Traceback (most recent call last):
  File "/home/dawn/.conda/envs/qap/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/home/dawn/.conda/envs/qap/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/dawn/.conda/envs/qap/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/dawn/.conda/envs/qap/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/dawn/.conda/envs/qap/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/home/dawn/.conda/envs/qap/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/dawn/.conda/envs/qap/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 486, in _run_interface
    proc.start()
  File "/home/dawn/.conda/envs/qap/lib/python2.7/multiprocessing/process.py", line 124, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Interface Function failed to run. 

So in the end we ended up using only the .csv outputs of qap_functional_temporal and qap_functional_spatial, and I ran all 294 participants one at a time :( (it took forever).

**Comment by pipitone** [comment]
Great write up. Some of these issues you should definitely create on github against the QAP project and get help from the developers. Specifically:
- installation difficulties, perhaps ask what they recommend and we/they can update their instructions
- write_report deleting output 
- qap_anatomical_spatial incorrect outputs, but we'd need erin to give specifics before reporting this one
- the errors with more than one core/subject

IIRC the way I did things was to create a configuration file per subject and then just run separate qap processes per subject.

**Comment by pipitone** [comment]
Dawn, can you also point me to where you have this set up correctly so I can take a look at what you've done?

**Comment by DESm1th** [comment]
Oh! Oops. I forgot that part. The copy of their repo that I got working is under /projects/dawn/quality-assessment-protocol/ and the environment is in /home/dawn/.conda/envs/qap on golgi.

**Comment by pipitone** [comment]
Just an update, but I was able to install QAP using the following incantations. Note that I'm using miniconda only so that I have a clean environment to play around with; a regular conda environment ought to work just as well. 

```sh
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
bash Miniconda2-latest-Linux-x86_64.sh  -b -p $PWD/cenv
export PATH=$PWD/cenv/bin:$PATH
conda config --append channels conda-forge
conda config --append channels pmuller
conda install pillow scipy pyyaml pandas nitime nibabel nipype seaborn pygraphviz
pip install qap
```

**Comment by pipitone** [comment]
@DESm1th have you seen this error? I'm running the anatomical pipeline on a single subject which runs almost to completion but fails attempting to update a CSV file. From the end of the output:

```
160802-00:39:47,309 workflow INFO:
         Executing node qap_anatomical_spatial_to_csv in dir: /imaging/scratch/kimel/jpipitone/qap/working/SPN01_CMH_0001/01/SPN01_CMH_0001_01_01_T1_02_SagT1_BRAVO/qap_anatomical_spatial_to_csv
/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/algorithms/misc.py:870: UserWarning: Python module lockfile was not found: AddCSVRow will not be thread-safe in multi-processor execution
  warn(('Python module lockfile was not found: AddCSVRow will not be'
160802-00:39:47,349 workflow ERROR:
         ['Node qap_anatomical_spatial_to_csv failed to run on host dev01.']
160802-00:39:47,354 workflow INFO:
         Saving crash info to output/crash-20160802-003947-jpipitone-qap_anatomical_spatial_to_csv-c79e0c4e-1d21-4cf0-8a30-0aa56e716f8b.pklz
160802-00:39:47,356 workflow INFO:
         Traceback (most recent call last):
  File "/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/imaging/scratch/kimel/jpipitone/qap/qap/lib/python2.7/site-packages/nipype/algorithms/misc.py", line 897, in _run_interface
    with open(self.inputs.in_file, 'w') as f:
IOError: [Errno 2] No such file or directory: 'output/qap_anatomical_spatial.csv'
```

The subject list config file looks like: 

```yaml
SPN01_CMH_0001:
  '01':
    anatomical_scan:
      SPN01_CMH_0001_01_01_T1_02_SagT1_BRAVO: /imaging/scratch/kimel/jpipitone/mb_test/SPINS/data/nii/SPN01_CMH_0001_01/SPN01_CMH_0001_01_01_T1_02_SagT1-BRAVO.nii.gz
```

The pipeline configuration file looks like:

```yaml
num_cores_per_subject: 1
num_subjects_at_once: 1
output_directory: output
working_directory: working
write_all_outputs: True
template_brain_for_anat: /KIMEL/quarantine/FSL/5.0.9/build/data/standard/MNI152_T1_2mm_brain.nii.gz
template_skull_for_anat: /KIMEL/quarantine/FSL/5.0.9/build/data/standard/MNI152_T1_2mm.nii.gz
write_report: False
write_graph: False
```

I ran `qap_anatomical_spatial.py`

**Comment by DESm1th** [comment]
Hey Jon!

Thanks for finding an easier way to get qap working. I encountered the "Python module lockfile was not found: AddCSVRow will not be..." error at some point but definitely not with qap_anatomical_spatial, because I never attempted to run that one during any of the iterations after Erin told me the outputs were broken/a work in progress. 

I can't remember what I did to cause the same error, but I noticed that my config files set write_all_outputs to False, and I know that at one point I tried with 'True' set and it didn't work. I don't remember if that 'lockfile not found' error was the cause at the time, though. I should take notes in the future when I do these sorts of things :(

**Comment by edickie** [comment]
Hey guys,

Yeah, I should clarify.

I compared the qap_anatomical_spatial outputs to my own visual qc of the
freesurfer outputs from ABIDE and they didn't really match up :-(.

This issue came up in conversation with Gabe, who told me that he did the
same thing (and, took a look at QAP's source code) and came to conclude
that the QAP anatomical spatial numbers were not very valid :-(.

However, the QAP functional pipeline numbers do look good. They match up
well with my own visual QA assessments and Gabe approves of the source code.

So we should focus on the functional pipelines right now.

Thanks,
Erin

**Comment by pipitone** [comment]
Update. `qap_functional_temporal.py` runs to completion. 

btw, I had to revert to using the anaconda version of `graphviz` because "pmuller"'s doesn't support png output.

**Comment by pipitone** [comment]
I've just added `dm-proc-qap.py` to datman which does the basics of setting up and running QAP on a datman project. See the commit message for more info about other bits that could be added to this proc script.

The QAP code itself is still in a quite a bit of flux and seems quite flaky to me in many ways. Nevertheless, I will create a QAP module based on the current code based on my instructions above before closing out this issue.

**Comment by pipitone** [comment]
Okay, I've added `qap/20160104`. The module does not load AFNI or FSL, but those are requirements for QAP to run.
