### ISSUE TITLE
datman held jobs never cancelled from the queue

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#650]
We seem to he having a problem with the new qbatch datman with the held jobs.

It seems like, when one of the many dependancies exist with errors, the held jobs do not get cancelled from the queue. 

See email train below...

Jon, any idea of what is going on?

> Hi,Erin
> I think it sound like qbatch issue. It’s will be appreciated you can clean the held jobs.
> Best Regards!
> Andy Wang
> Erin Dickie
> [Reply All]
> Sent Items
> Tuesday, August 02, 2016 2:00 PM
> Hi guys,
> 
> I've been submitting the clevis jobs. It's maybe a strange cause because all held jobs we submitt are waiting for multiple jobs to finish without errors. All the dependant jobsSo it seems like if one of the dependant jobs finishes with errors, the held jobs are not getting killed..
> 
> I also have this problem in my own account. But he clevis account has it more.
> 
> Do you want me to kill all of clevis' held jobs?
> 
> Thanks,
> Erin
> Andy Wang
> [Reply] [Reply All] [Forward]
> Actions
> In response to the message from Erin Dickie, 7/20/2016
> To:
>  Erin Dickie‎; David Rotenberg 
>  
> Tuesday, August 02, 2016 1:11 PM
> You replied on 8/2/2016 2:00 PM.
> Hi,Erin
> Could you please tell me clevis account user email. We found some job hold with depend afterok directives.
> We are not sure the previous job is ok or have error. Usually if the depend job exit with error, the subsequent jobs will be killed due to "dependency not met".
> We want cleves’s help to clarify whether the pbs have some bug.
> Best regards!
> Andy Wang

**Comment by pipitone** [comment]
I suspect this is the expected behaviour in PBS but I'll have to check the qsub man page in a bit. IIRC tho, afterok only runs the job of the dependencies complete without error and holds otherwise.

**Comment by pipitone** [comment]
Nope, I'm wrong. Dependent jobs should die if the jobs they depend on exit. 

I think I've found the problem though: qbatch will happily set up jobs to be dependent on already completed jobs (because their names/IDs match whatever pattern you gave them). PBS (our version?) holds the dependent job forever.

To reproduce:
```sh

$ echo "hello" | qbatch -
163592.mgmt2.scc.camh.net

# wait until 163592 has completed

$ echo "hello" | qbatch --depend 163592.mgmt2.scc.camh.net -
163593.mgmt2.scc.camh.net

$ qstat | grep 163593
163593.mgmt2               STDIN            jpipitone              0 H short1n   

$ qstat -f 163593 | grep depend
    depend = afterok:163592.mgmt2.scc.camh.net@mgmt2.scc.camh.net
```

**Comment by pipitone** [comment]
ps. I'm not entirely sure how to tell which version of TORQUE we're running, but qsub --version returns 3.0.4.  When I load the TORQUE/6.0.1 module, I get an error using qsub ("unable to communicate with headnode"), so I'm not sure what the deal is.

**Comment by pipitone** [comment]
I've emailed Andy (cc'd Erin) about this issue with PBS. We are [planning to patch qbatch](https://github.com/pipitone/qbatch/issues/119) so that it doesn't set up job dependencies on already completed jobs, but there will still be cases we can't avoid (e.g. jobs that complete in the time between when qbatch checks for running jobs, and when qbatch submits the job). Hopefully Andy plans to update PBS to a newer version on the SCC. 

In the meantime, we'll just have to kill jobs that are stuck in hold. ;-(
