### ISSUE TITLE
PASD_CMH_PASD2_01 QC broken image links

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#719]
Investigate

**Comment by DESm1th** [comment]
Hey Navona, isnt this one of the pages we had issues with recently? If all of the images are there try deleting the .html page and regenerating first. Otherwise try deleting everything in their qc folder and running qc_html on just that subject (with AFNI, FSL and minc-tools modules loaded) before you worry about it.

**Comment by navonacalarco** [comment]
Dawn you shouldn't be working! But thank you!

**Comment by DESm1th** [comment]
I'm not! I'm drive by commenting :D goodluck!

**Comment by navonacalarco** [comment]
Alright. I think I followed Dawn's instructions, but it seems that, though the TechNotes are XNAT, they're getting pulled into the subject folder in our system, as opposed RESOURCES, and thus not being linked. Will investigate with @tomwright01 on Monday.

**Comment by tomwright01** [comment]
The XNAT project id for this project is not the same as the project title
Title: PASD01
ID: ASDN01
The XNAT archive dir is: '${XNAT_ARCHIVEDIR}/ASDN01/arc001'

Updated the XNAT_Archive setting in project_settings.yml to reflect this.
from: XNAT_Archive : '${XNAT_ARCHIVEDIR}/PASD01/arc001'
To: XNAT_Archive : '${XNAT_ARCHIVEDIR}/ASDN01/arc001'

Ran command in `archive/data/PASD/metadata/recreate_pipeline.sh` to recreate `archive/data/PASD/bin/run_data_kimel.sh`
