### ISSUE TITLE
Modify expected scan paramters for 'T2DEfseXL' across CAMH studies

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#751]
This is related to the header differences that we've been seeing in across studies in several CAMH T2 scans. We contact Sofia to ask what the parameters should be, this is her response:

> I looked into those parameters, it looks like your automated detection
> of parameters is having trouble with the dual-echo sequence
> (that's what the 'DE' in 'T2DEfseXL' stands for). A dual echo sequence
> produces images with 2 different contrasts (PD & T2w) at 2 different
> echo times: TE1=11ms, TE2=89ms. So- I am guessing that the echo number
> should alternate between 1 and 2, depending on whether you are looking
> at the PD-weighted (shorter TE) or the T2w (longer TE). Both those TE
> values are OK, one for each echo. The Flip Angle is set to 125 deg for
> all studies, not sure why you have an expected value of 90?

So, we need to adjust the expected parameters for 'T2DEfseXL' across CAMH studies.

Could use some help with this in terms of time and also how best to approach. :)

**Comment by josephdviviano** [comment]
We have two options:

1) ignore these scan types entirely.
2) make is so that we always check the right dicom file from the upload.

Right now, the headers are 50/50 split between two scans for this file type, so with every upload, there's a 50% chance of this happening (this is a known issue).

I vote to ignore because these scans are just used for visual inspection, not analysis.

@DESm1th @tomwright01 @navonacalarco @edickie what do you think?

**Comment by navonacalarco** [comment]
I spoke briefly with Colin and also he suggested that, given the current use, we could ignore.

I'm unsure of when looking at 'T2DEfseXL' might be important for analysis. Colin suggested the original intent was for these scans to actually be used for DTI coregistration, but that's since changed. If there's any chance that this data could be used for more than visual inspection in the future, my vote would be to write things to check the right dicom file.

**Comment by josephdviviano** [comment]
Yes, the thing that would need to change would be the thing that looks through each dicom header. Instead of checking only one, we would need to check every single one, and find all the unique headers. Then we would need to compare with each of the unique headers.

This could potentially take 100 times as long as the current method. Since we can get most of the information we need by just looking at the images, I'd vote we just stick with that.

Any objections?

**Comment by navonacalarco** [comment]
Not from me unless there is any chance that this data could be used for more than visual inspection in the future.

**Comment by josephdviviano** [comment]
@navonacalarco I also mean that you can get a sense of whether the data is useful just by looking at it. Parameter changes on the MRI machine usually don't actually matter in a real way. You need to really change the settings to get the image to look different.

For the DTI stuff, we were just using it for registrations, so if the image looks good, it is good.

As an aside, can you get Colin to sign up for github and start checking in on these conversations? It's a pain communicating with him because he misses out on so much.

**Comment by navonacalarco** [comment]
@josephdviviano Great, thanks. Should we be changing the old checkheaders script, or is this now rolled into qcmon?

**Comment by navonacalarco** [comment]
@josephdviviano Just wanted to follow up: the same errors re: OblAx-T2DEfseXL are appearing in the most recent log (2016-09-18-check-headers.log).

**Comment by josephdviviano** [comment]
Yes that's because we're still checking those scan types...

**Comment by navonacalarco** [comment]
So should we be changing the old checkheaders script, or qcmon? Or are we waiting on some other changes to be made?

**Comment by navonacalarco** [comment]
@josephdviviano Just wanted to check in about this - we're seeing header diffs re: OblAx-T2DEfseXL on new SPINS QC pages

**Comment by josephdviviano** [comment]
Sorry I keep getting distracted by other things.

I just removed all `_PDT2_` scans from the standards folders across all studies, so this problem should go away.

**Comment by josephdviviano** [comment]
Neither script needed to be changed, I just needed to remove the gold standard dicom files.

**Comment by navonacalarco** [comment]
Good to know. Thank you. :)
