### ISSUE TITLE
freesurfer / HCP pipelines not being run on new data

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#799]
@edickie , looks like we don't have freesurfer / HCP outputs for some of the newer spins subjects. Any idea what's going on (these are being run on the SCC, correct?)

**Comment by edickie** [comment]
Me made a decision last month to have @navonacalarco run the pipelines manually when she finished QC, I think the last time we did this together was a couple of weeks ago. So there might be some newer misssing.

Also, pipelines on the scc are set up to not run for new subjects who have not been qced. So that might also be an issue..

I just sshed into the scc and manually ran the pipelines, so we should have everything by Monday.

**Comment by navonacalarco** [comment]
Yes, what Erin said is right. I have not ran this at least since the QC was fixed earlier this week, and there's still a few outstanding subjects to QC for SPINS, so it won't be entirely complete.

Thanks for re-running it again, Erin. I'll be more on top of this going forward and the QC list is getting smaller. Is the consensus that the pipelines should be done every day?

**Comment by josephdviviano** [comment]
@edickie @navonacalarco 

I'm assuming we're doing this because erin's checklist-checking code is broken? It used to do this (run data only after QC) automatically.

let's talk about running the data ad-hoc vs just running it nightly at our next meeting. It seems to me like it would be better for us to just run the pipelines on all that data, regardless of QC status, since we have code that will delete outputs if they are later blacklisted. 

It will prevent wild goose chases like the one I'm currently on.

**Comment by edickie** [comment]
The checklist code is working, that is why (back when Navona was doing all
the qc) we felt it would be more efficient to have Navona manually submit
pipelines once she had finished signing off on a substantial number of
subjects.

I agree that, now that Navona is not signing off on all the checklists, it
makes sense to rethink this.

Our code does an ok job deleting files related to blacklisted subjects, but
it doesn't nessarily do the same for csv rows (and database enties?)
related to the outputs from bad scans..

**Comment by tomwright01** [comment]
1. Updated `/archive/code/bin/runall_pipelines_scc.sh` so project pipelines are submitted to scc over shh.
2. Updated main cron job to run `runall_pipelines_scc.sh` nightly
3. Updated ansible templates to match current cron settings
