### ISSUE TITLE
blacklists are out of control :O

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#800]
hey all,

I'm noticing that a good number of my resting-state pipelines are failing due to missing data. I've noticed that this is happening in some cases because **both** copies of a scan were blacklisted.

Case in point: `SPN01_CMH_0017_01`.

This subject has two `OBS` scans. The first is truncated was manually blacklisted a while back. However in the `blacklist.csv` file I now find:

```
...
 157 SPN01_CMH_0017_01_01_OBS_10_Ax-Observe-Task      SPINS-IMOBS-datacleaning-extra-scan                           
 160 SPN01_CMH_0017_01_01_OBS_09_Ax-Observe-Task              SPINS-IMOBS-datacleaning-extra-scan
 161 SPN01_CMH_0017_01_01_OBS_10_Ax-Observe-Task              SPINS-IMOBS-datacleaning-extra-scan
...
```

I'm thinking the auto-blackllist program has gone wild. Anyone know where to look?

**Comment by josephdviviano** [comment]
@edickie @DESm1th in particular

**Comment by DESm1th** [comment]
Hmm. I dont know anything about things being automatically blacklisted (and
I havent manually added anything to the blacklist, ever) but I did go
through and remove all the blacklisted files today that were lingering in
the archive since Julyish which is probably why things are failing now. The
blacklist may have been like that for a while

**Comment by josephdviviano** [comment]
@DESm1th thanks , might have been @edickie or Jon way back when ... I'll wait to hear from her.

**Comment by navonacalarco** [comment]
Yikes, that looks like something I did fairly recently, actually. I generated a list with the number of TRs for all IMOBS scans in the file system, and blacklisted what was shorter than expected. Not sure why series 10 appears here twice, but it should be that both series 9 and 10 are truncated if both appear here.

Are there similar cases other than SPN01_CMH_0017_01? I ask because something odd might have gone on with that participant -  I'm pretty sure there were a few issues raised by Colin about that subject - I'll dig through my email to check - and perhaps things got added twice accidentally. Will look closer tomorrow.

**Comment by edickie** [comment]
I'm pretty sure that's acutally correct.  I think I tried to unblacklist
and process the longer of the two scans from one participant. (probably
SPN01_CMH_0017_01)..and it failed because there still were not enough TR's,
so I re-blacklisted it...

**Comment by josephdviviano** [comment]
Hi @edickie @navonacalarco 

you're right, both of those scans are truncated. thanks! I would suggest that we put a more useful description in the blacklist file next time ('truncated' instead of 'SPINS-IMOBS-datacleaning-extra-scan')
