### ISSUE TITLE
ASDD scans not making it into our system from MR server

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#824]
- [ ] ASDD_CMH_EF043_01_01 - we have 'scan completed', not in XNAT, not on MR server
- [ ] ASDD_CMH_EF042_01_01 - no 'scan completed', not in XNAT, on MR server
- [ ] ASDD_CMH_HEF017_02_01 - we have 'scan completed', not in XNAT, on MR server

**Comment by navonacalarco** [comment]
Update: RA is resubmitting 'scan completed' for ASDD_CMH_EF042_01_01. Must have been an internet connectivity issue as she attempted to. Indicated over email lots of issues with scan.

**Comment by tomwright01** [comment]
sftp to camhpet wasn't connecting correctly. Possibly due to changed server id or possibly due to throttling. Resolved by @josephdviviano 
Scans are now in xnat, so correctly linked and uploaded. Xnat-extract seems to have failed.

**Comment by tomwright01** [comment]
project configuration scripts point to `/mnt/tigrlab/xnat/...`
`/mnt/tigrlab/xnat/.../` is a backup of `/mnt/xnat/`
cron jobs _failed_ because the backup hadn't completed before the scripts tried to run.

**Solution**
Modify `XNAT_ARCHIVE` path in `*_managment.sh` scripts to point to `/mnt/xnat/...`

**Effects**
`xnat-extract.py` will only run on tigrsrv
