### ISSUE TITLE
PASD01 QC pages are missing certain scan acquisitions

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#841]
Met with Avi, noticed that we don't have all expected scans on QC page - need to update.

**Comment by djoverton** [comment]
Just to clarify, this seems to only be the case with some pages (e.g., PASD_CMH_PASD4_01 looks fine). I will re-run dm-qc-report.py.

**Comment by djoverton** [comment]
Dawn is fixing a couple of bugs with dm-qc-report.py before this can be done, but looking at the pages a bit more closely it doesn't look like a page generation error, we're missing the data for those scans.

**Comment by DESm1th** [comment]
I've rewritten all the QC pages so if anything is still missing as Dawson said it's missing data.

**Comment by navonacalarco** [comment]
Thanks Dawn and Dawson. 

@avidehg, things should be good to go. Can you take a look?

**Comment by avidehg** [comment]
Hi all, thank you so much for working on this. Would appreciate it if you would please look into the following issues regarding "PASD_CMH_PASD9_01_01":

- DTI 1000 not brought in to QC page
- DTI 3000 not brought in to QC page
- ASL not brought in to QC page
- Amygdala images missing 
- DTI 60+5 (2.0) images missing
- PDT2_08_OblAxT2-DEfseXL.nii.gz, will you please clarify whether this is a PD or T2 scan? We have both T2 and PD scans in tech notes, therefore one is missing images and data

**Comment by DESm1th** [comment]
Hey Avi,

The missing DTI33-1000, DTI33-3000, ASL, and PD were all due to issues in the export info which has now been corrected. I made sure all the data has downloaded correctly so this shouldn't be a problem again (but let me know if there are further problems!)

The missing Amygdala image was due to a missing handler for the tag 'TRG' in dm-qc-report, this is fixed now.

The DTI60+5 (2.0) does not appear to be missing, but the DTI60+5 (2.9) is and the tech notes state this is because the session was dropped so no issue here.

The PDT2_08_OblAxT2-DEfseXL.nii.gz is both a PD and a T2 combined into one. The separate PD session (session 06) was previously not being download (this is fixed) so now it shows up on the QC page in addition to the PD split from the PDT2 image.

I'm still looking into why the T2 from the PDT2 does not show up, though. Will update and close the issue when this is resolved.

**Comment by navonacalarco** [comment]
Awesome! Thanks Dawn. :)

**Comment by avidehg** [comment]
Dear Dawn, 

Thank you so much for your help. Will you please also look into why:

-  DTI 1000 not brought in to QC page?
- DTI 3000 not brought in to QC page?

And also, only the image for DTI60+5 (2.0) is missing.....

Thanks so much!

**Comment by DESm1th** [comment]
Hi Avi,

Ah! I see what you mean about the DTI60+5 (2.0) missing now. I was looking at the table, so I didn't notice the image itself was gone. This was another missing handler in dm-qc-report which I've added in, so this should be fixed now.

I can't figure out what you mean about the DTI 1000 and 3000 though. When I open the page they're both on the table at the top of the page, and they both have a B0 montage and a bvec directions plot. Could you describe more what should be there but isn't?
