### ISSUE TITLE
DTI3T checklist.csv is lit

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#845]
![screen shot 2016-11-08 at 8 56 07 pm](https://cloud.githubusercontent.com/assets/13733654/20124751/cbc620e6-a5f6-11e6-9988-1ac9ea16636d.png)
![imgres](https://cloud.githubusercontent.com/assets/13733654/20124793/12a45eec-a5f7-11e6-8693-cbd18880efa9.jpg)

**Comment by DESm1th** [comment]
Yeaaaah. There's a lot of duplication in most of the checklist.csv files right now because there was a second (hidden) bug in dm-qc-report.py that meant my previous fix didn't completely solve the problem! I've fixed it in my copy (for realsies this time)... I should really hurry up and merge it and clean that up.. sorry D:

**Comment by josephdviviano** [comment]
Protip: you can delete duplicate lines from text files via

`cat filename.txt | uniq > newfilename.txt`

**Comment by navonacalarco** [comment]
Thanks both!
