### ISSUE TITLE
MPR/ZHP causing problems for SPINS checklist.csv?

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#866]
Hey guys,

I'm not exactly sure what leads to "no checklist entry" (other than deleted qc pages before re-run), but I noticed that there's 3 such entries on dm-qc-todo.py for SPINS, and all are for the new SPINS site codes MRP or ZHP:

No checklist entry for /archive/data-2.0/SPINS/data/nii/SPN01_MRP_P001_03
No checklist entry for /archive/data-2.0/SPINS/data/nii/SPN01_MRP_P005_01
No checklist entry for /archive/data-2.0/SPINS/data/nii/SPN01_ZHP_0060_01

Is it possible that there's an error with checklist generation for the new site codes?

**Comment by DESm1th** [comment]
I've been keeping an eye on this, because there's quite a few scans that just occasionally get ignored by qc-report and I'm not sure why. I'll manually generate them all today and let you know if I figure this one out..

**Comment by DESm1th** [comment]
I've finished manually generating the pages. There weren't any errors or crashes when run manually so there appears to be no issue here. 

I suspect that all the missed subjects are just being missed because the pipeline is crashing for other reasons before it gets to them, since there have been so many changes to datman lately, but all the same I'll keep an eye on things.
