### ISSUE TITLE
Investigate why there are no checklist entries for certain PACTMD, SPINS, and DTI1.5T scans

### ISSUE THREAD

**Issue by djoverton** [TIGRLab/admin#909]

**Comment by djoverton** [comment]
No checklist entry for /archive/data-2.0/PACTMD/data/nii/PACTMD_CMH_0100029_02
No checklist entry for /archive/data-2.0/PACTMD/data/nii/PACTMD_CMH_0100032_02
No checklist entry for /archive/data-2.0/PACTMD/data/nii/PACTMD_CMH_0110023_01
No checklist entry for /archive/data-2.0/PACTMD/data/nii/PACTMD_CMH_0950053_01
No checklist entry for /archive/data-2.0/PACTMD/data/nii/PACTMD_CMH_3060070_02
No checklist entry for /archive/data-2.0/PACTMD/data/nii/PACTMD_CMH_3060075_01

From Nov. 28 log:
ERROR:datman.xnat:Failed to open file:/archive/data/PACTMD/data/dicom/PACTMD_CMH_0100029_02_01.zip with excuse:
ERROR:/archive/code/datman/bin/dm2-xnat-upload.py:Failed uploading archive to xnat project:PACT01 for subject:PACTMD_CMH_0100029_02_01
2016-11-28 08:18:25,833 - /archive/code/datman/bin/dm2-xnat-upload.py - ERROR - Failed uploading archive to xnat project:PACT01 for subject:PACTMD_CMH_0100029_02_01

From Nov. 23:
ERROR:/archive/code/datman/bin/dm2-xnat-extract.py:Failed downloading resource archive from:PACTMD_CMH_0100032_02_01
2016-11-23 11:44:03,174 - /archive/code/datman/bin/dm2-xnat-extract.py - ERROR - Failed downloading resource archive from:PACTMD_CMH_0100032_02_01

Seems like this isn't an issue with only one script -- looking into it further.

**Comment by DESm1th** [comment]
Hey Dawson,

To add to this, the lack of checklist entries has popped up off and on the past couple months. Almost always (as far as I could tell) it was due to the pipeline failing somewhere along the line and the qc-report script just not getting a chance to be run. Not sure if that's the case this time though.

**Comment by djoverton** [comment]
It's definitely a case of generate_qc_report failing (from the logs it appears for many different reasons), which causes an exception and prevents the function that adds the session to the checklist from being run. I've moved the code that adds it to the checklist to before the report is created, to make debugging a bit less confusing.

**Comment by DESm1th** [comment]
Just as an update to this, I suspect that the problem is that sometimes multiple queue jobs try to update the checklist.csv file at the same time and all but the first receives an error that causes the write to fail. As evidence for this, two STOPPD scans ran last night and didn't receive checklist entries despite the pages being generated successfully and despite the fact that Dawson's change should mean an entry is created before the page is created. When I ran them from the command line with --rewrite no issues could be replicated.

If the checklist write failed, it should have printed an error message but currently the queue swallows all output from the scripts. So for now I'm going to work on creating a logging server and setting up qc-report to use a syslogHandler when it's run on the queue to make debugging easier.

**Comment by DESm1th** [comment]
Just as an update: I've added a script to act as a logging server to our github repo, and modified qc-report to be able to use it. I'll add it to the run scripts on Monday, so it's not potentially breaking things over the weekend if there's any bugs lurking.

I also discovered that dm-qc-todo had a bug in it that was causing some DTI15T participants to show up as missing checklist entries even though they were in the checklist. I fixed this as well.

**Comment by tomwright01** [comment]
Hey Dawn,
I think this logserver should get an issue of it's own. Can you create one,
telling us where we can see the logs etc.
Thanks,
tom

**Comment by DESm1th** [comment]
It looks like this can finally be closed! The log server caught two checklist writes on 2016-12-23 that failed, and since then I've added code to dm-qc-report to re-attempt the checklist update another two times when it fails.

I'll keep an eye on the logs, as always. We might still get the occasional subject reported as not having a checklist entry because all of their data wasn't downloaded and qc-report couldn't run, etc. but dm-qc-report itself shouldn't be the problem anymore.
