### ISSUE TITLE
Dashboard: user signout issue

### ISSUE THREAD

**Issue by leepropp** [TIGRLab/admin#970]
@djoverton @tomwright01 

We are looking at the Dashboard and noticed that, when one person signs out of the Dashboard (using User > Logout), the user is not logged out of GitHub. So, to actually log out of the Dashboard, it seems that you need to go to GitHUb to logout as well.

**Comment by djoverton** [comment]
Hi @leepropp, this is intentional, since the user may want to sign out of the Dashboard but remain signed in to GitHub. I'm assuming the issue you are having is switching users, since if you sign out of the Dashboard but immediately authenticate again, there is no option to authenticate as a user other than the one which is logged in. To get around this for now, simply log out of your GitHub account separately and then log in with the other user (or attempt to authenticate while not logged in, which will prompt you to log in with a different user).

I agree that offering an option to authenticate as a user other than the one which is logged in might be useful; we will consider adding this in the future.

**Comment by leepropp** [comment]
Thanks!

**Comment by navonacalarco** [comment]
Thanks Dawson!
