### ISSUE TITLE
SPINS: compare PI data on new ZHP and MRP scanners

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#985]
This can be done now that we have all data uploaded

**Comment by navonacalarco** [comment]
@josephdviviano Some of the phantom IDs from this year haven't been updated in metadata/human-phntom-IDs. 

Attached is an easier-to-read summary of what we're missing. Can you please add? 

[SPINS_phantom_IDs.xlsx](https://github.com/TIGRLab/admin/files/667496/SPINS_phantom_IDs.xlsx)

**Comment by josephdviviano** [comment]
Hi Navona, there are some mistakes in the spreadsheet you sent me.

Regardless of whether there was a site switch or not, the new sites should have an `_03` to indicate year 3. Otherwise it gets very confusing. 

I'll do what I can with the spreadsheet you sent me and send it back to you. I agree that this new format is far less confusing so we should replace the orig file when im donw.

`SPN01_ZHP_P001_02` and `SPN01_MRP_P001_03`

**Comment by josephdviviano** [comment]
Hi Navona,

I fixed a few mistakes and renamed some of the subjects in XNAT. The human-phantom-IDs.csv file in metadata is now updated.

I've sent out an email asking whether one or both of the 'extra' subjects was Miklos. It looks to me like we have all of the data.

I'm going to delete all of the human phantoms from the filesystem -- you will want to reexport from XNAT to update the names.

**Comment by josephdviviano** [comment]
Confirmed that both subjects were Miklos. I've removed all human phantoms from the filesystem.

**Comment by navonacalarco** [comment]
Thanks. Do you mind posting or sending me the updated spreadsheet?
